# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='highest',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
