# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auto_20170707_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
